### ISSUE TITLE
Why not use an external editor?

### ISSUE THREAD

**Issue by PaperOrb** [0Tick/a1111-mini-paint#1]
Sorry for the rude sounding title, but I'm just wondering what the use of having a photo editor in the webUI is? I also wondered this about the recent photopea extension but no one answered. It seems like you're basically getting "send to txt2img and img2img" type of features in exchange for a heavier webUI and less photo editing features than gimp or photoshop.

**Comment by ostap667inbox** [comment]
It's a question of "if I'm comfortable with something, why isn't everyone using it" :)
Some people may find it faster and more convenient to use the Photopea tab or this editor for simple tasks.

**Comment by 0Tick** [comment]
> Some people may find it faster and more convenient to use the Photopea tab or this editor for simple tasks.  
This was mainly the reason. Opening an image editor importing the image, making changes, saving/exporting and then importing it again just takes too much time. If you want to heavily edit the image, I would also use an external Programm but for not too complex changes. It just is too time consuming.  
This extension has the benefit of also working offline when compared to photopea. Also you don't get any ads

**Comment by PaperOrb** [comment]
Fair enough points I suppose. It sounds less valuable to me personally, but I'll try it out for the heck of it just to see whether the time savings are substantial. Thanks.
