### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kakachiex2** [0Tick/a1111-mini-paint#12]
Helo 0tick, great work on this I love it I have some feature request I'm working with this on comfy is a painter node and is amazing but I dont like this scrible brush I would like to see brush system like MyPaint is open source and death but the app is amazing  and the brush system is independent library from the app can you integrate it and add mirror feature; here is some example of what Im working on with paint node and my paint sketches.
![Screenshot 2023-12-07 232956](https://github.com/0Tick/a1111-mini-paint/assets/1762112/a767db56-4839-4d73-912a-fe4d695cceb1)
![Screenshot 2023-12-09 194006](https://github.com/0Tick/a1111-mini-paint/assets/1762112/e4c49534-0416-4538-941e-172d55bb1983)

**Comment by kakachiex2** [comment]
The pressure sensitive don't work what I can do.

**Comment by kakachiex2** [comment]
And when I activate pressure the stroke look faceted here is an example without pressure and with pressure
![Screenshot 2023-12-10 024535](https://github.com/0Tick/a1111-mini-paint/assets/1762112/573f3603-5aaa-4063-ba83-0cb2d59d9801)

**Comment by 0Tick** [comment]
> And when I activate pressure the stroke look faceted here is an example without pressure and with pressure ![Screenshot 2023-12-10 024535](https://private-user-images.githubusercontent.com/1762112/289341986-573f3603-5aaa-4063-ba83-0cb2d59d9801.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDgxNzEsIm5iZiI6MTcwMjQwNzg3MSwicGF0aCI6Ii8xNzYyMTEyLzI4OTM0MTk4Ni01NzNmMzYwMy01YWFhLTQwNjMtYmE4My0wY2IyZDU5ZDk4MDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMTkwNDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE3MTU5YWY0Y2FmMGI0ODJkYzZiMzhkZTk1NDE0MjRhMDg5YTYwZDY0Y2M2NTk2ZTY0ZmY3ODE1ZWMyMTBiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wJFuciJ5YpM9FGHxQI9xdi4igxGGOltmo8q5KW8WBM0)

Is this still occuring? I was not able to replicate it. Regarding your feature request you should probably ask again [here](https://github.com/viliusle/miniPaint) as this is the original editor and what i based this project on. I am not familiar on how the brush system is implemented and wont be able to integrate a new brush system.
