### ISSUE TITLE
Bug: Sending the edited image as "Image2Image Init Image" instead sends the image to inpaint.

### ISSUE THREAD

**Issue by anonCantCode** [0Tick/a1111-mini-paint#2]
Both of the options presented when sending to img2img instead send the image to inpaint.

**Comment by joelon1** [comment]
I noticed the same thing, when sending to img2img instead sends it to inpaint. I cant beleave someone promoted this, zero testing.

**Comment by 0Tick** [comment]
Should be fixed now

**Comment by anonCantCode** [comment]
@joelon1 That's pretty rude. It's a free extension and mistakes happen.
@0Tick Thanks for the fix!

**Comment by joelon1** [comment]
Yes, I was rude. but there is a difference between free and broken. having said that i apologise
