### ISSUE TITLE
Forge is missing "Send image to miniPaint tab" button due to missing .form id under #image_buttons_txt2img, possibly due to Gradio 4.40

### ISSUE THREAD

**Issue by solonrice** [0Tick/a1111-mini-paint#20]
It appears that the "Send image to miniPaint tab" button is not being added with the new Forge using Gradio 4.40. The console blows up with an error at `window.parent.gradioApp().querySelector('#'.concat(t, ' .form')).appendChild(o)`.

**Comment by 0Tick** [comment]
I took a look at it and it seems like the new Gradio Version messed a lot of things up. Might take a while until i can get to fix them

**Comment by lost753541** [comment]
I'm looking to switch to forge but minipaint has become such an essential shortcut for editing in my workflow. Any chance this will be fixed soonish? Any possible workarounds?

**Comment by 0Tick** [comment]
Should be fixed now. You will need to create a new canvas for the controlnet elements first though as i am not able to do that myself. Appart from that everything should work
