### ISSUE TITLE
Standalone minipaint in Gradio 4

### ISSUE THREAD

**Issue by ikmalsaid** [0Tick/a1111-mini-paint#21]
Good day, I am hoping that you can release a standalone version of minipaint on gradio 4 (not a plugin for a1111/forge) as I want to study the integration of it with gradio framework.

Thanks!

**Comment by 0Tick** [comment]
As the original [miniPaint](https://github.com/viliusle/miniPaint) is a standalone web app, you might want to take a look at it, as the Gradio integration on this extension is limited to showing an iframe embedding this application and making the number of available controlnets acessible. The only python file in this repository is [this](https://github.com/0Tick/a1111-mini-paint/blob/main/scripts/mini_paint.py) one. I hope you find what you are trying to study
